# Generated by Django 3.2 on 2021-07-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EyeKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('row', models.IntegerField(blank=True, default=1)),
                ('col', models.IntegerField(blank=True, default=1)),
                ('label', models.CharField(blank=True, default='a', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Trunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
