# Generated by Django 3.2 on 2021-07-24 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyekey',
            name='trunk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eye_keys', to='trunk.trunk'),
        ),
    ]
