# Generated by Django 3.2 on 2021-07-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0002_eyekey_trunk'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='eyekey',
            order_with_respect_to='trunk',
        ),
    ]
