# Generated by Django 3.2 on 2021-07-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0003_alter_eyekey_order_with_respect_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eyekey',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='eyekey',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterOrderWithRespectTo(
            name='eyekey',
            order_with_respect_to=None,
        ),
    ]
