# Generated by Django 3.2 on 2021-07-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0004_auto_20210724_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyekey',
            name='col',
        ),
        migrations.RemoveField(
            model_name='eyekey',
            name='row',
        ),
        migrations.AddField(
            model_name='eyekey',
            name='type',
            field=models.CharField(choices=[('EYE', 'Eye Key'), ('ROW', 'Row Break'), ('COL', 'Column Break')], default='EYE', max_length=3),
        ),
    ]
