# Generated by Django 3.2 on 2021-07-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0005_auto_20210724_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyekey',
            name='col',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eyekey',
            name='row',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eyekey',
            name='label',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
