# Generated by Django 3.2 on 2021-07-25 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0006_auto_20210724_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='trunk',
            name='cols',
            field=models.IntegerField(default=4),
        ),
    ]
