# Generated by Django 3.2 on 2021-07-27 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0008_eyekey_col_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eyekey',
            name='type',
        ),
    ]
