# Generated by Django 3.2 on 2021-07-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trunk', '0009_remove_eyekey_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trunk',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
